package gui;

import bean.account.Account;
import bean.user.User;
import controller.AccountOverviewController;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

public class GUIAllAccounts extends JFrame {
    CardLayout cards;
    User user;
    AccountOverviewController accountOverviewController;
    GUIHomePage home;
    JPanel mainPanel, accountsPanel;

    public GUIAllAccounts(User u, GUIHomePage home) {
        this.home = home;
        cards = new CardLayout();
        mainPanel.setLayout(cards);
        this.user = u;
        this.accountOverviewController = new AccountOverviewController(u.getUid(), u.getUsername());
        update();
    }

    public void update() {
        mainPanel.removeAll();
        accountOverviewController.updateAccountList();
        List<Account> accounts = accountOverviewController.getAccountList();

        accountsPanel = new JPanel();
        accountsPanel.setLayout(new GridLayout(accounts.size(), 1));

        for (int i = 0; i < accounts.size(); i++) {
            Account a = accounts.get(i);
            JButton aBtn = new JButton(a.toString() + " #" + String.valueOf(i));
            aBtn.setName(a.toString() + " #" + String.valueOf(i));
            accountsPanel.add(aBtn);

//            GUIAccount acc = new GUIAccount(a, this);
//            mainPanel.add(acc.getMainPanel(), String.valueOf(i));
//            cards.s
//            mainPanel.add(acc.getMainPanel(), i);

            aBtn.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
//                    String i = aBtn.getName().split("#")[-1];
//                    int index = Integer.parseInt(i);
                    GUIAccount acc = new GUIAccount(a);
                }
            });

        }

        mainPanel.add(accountsPanel, "All Accounts");
        cards.show(mainPanel, "All Accounts");
    }

    public CardLayout getCards() {
        return cards;
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new CardLayout(0, 0));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
