package gui;

import bean.account.Account;
import bean.account.CheckingAccount;
import bean.account.SavingAccount;
import bean.account.SecurityAccount;
import bean.user.User;
import controller.CheckingAccountController;
import controller.LoanAccountController;
import controller.SavingAccountController;
import controller.SecurityAccountController;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class GUIDeposit extends JFrame {


    private JTextField depositInput;
    private JButton depositButton;
    private JButton goBackButton;
    private JPanel depositPanel;
    private Account account;


    public GUIDeposit(Account a) {
        this.account = a;
        setContentPane(depositPanel);

        depositButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String amt = depositInput.getText();
                if (amt == "") {
                    JOptionPane.showMessageDialog(null,
                            "Missing deposit amount",
                            "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    double depAmount = Double.parseDouble(depositInput.getText());
                    if (depAmount <= 0) {
                        JOptionPane.showMessageDialog(null,
                                "Please enter deposit amount greater than 0",
                                "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    if (account.getType() == Account.AccountType.SAVING) {
                        SavingAccountController savController = new SavingAccountController((SavingAccount) account);
                        if (!savController.deposit(depAmount)) {
                            JOptionPane.showMessageDialog(null,
                                    "Deposit not success.", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } else if (account.getType() == Account.AccountType.CHECKING) {
                        CheckingAccountController ckController = new CheckingAccountController((CheckingAccount) account);
                        if (!ckController.deposit(depAmount)) {
                            JOptionPane.showMessageDialog(null,
                                    "Deposit not success.", "Error", JOptionPane.ERROR_MESSAGE);
                        }

                    } else if (account.getType() == Account.AccountType.SECURITY) {
                        SecurityAccountController secController = new SecurityAccountController((SecurityAccount) account);
                        if (!secController.deposit(depAmount)) {
                            JOptionPane.showMessageDialog(null,
                                    "Deposit not success.", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null,
                                "cannot deposit money to loan account", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        });
    }

    public JPanel getDepositPanel() {
        return depositPanel;
    }

    public JButton getGoBackButton() {
        return goBackButton;
    }

    public JButton getDepositButton() {
        return depositButton;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        depositPanel = new JPanel();
        depositPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 4, new Insets(0, 0, 0, 0), -1, -1));
        depositPanel.setBorder(BorderFactory.createTitledBorder(null, "Deposit", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JLabel label1 = new JLabel();
        label1.setText("Please enter the amount of money you want to deposit:");
        depositPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        depositInput = new JTextField();
        depositInput.setText("");
        depositPanel.add(depositInput, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 4, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        depositButton = new JButton();
        depositButton.setText("Deposit");
        depositPanel.add(depositButton, new com.intellij.uiDesigner.core.GridConstraints(2, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        goBackButton = new JButton();
        goBackButton.setText("Go Back");
        depositPanel.add(goBackButton, new com.intellij.uiDesigner.core.GridConstraints(3, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return depositPanel;
    }

}
