package gui;

import bean.user.User;
import controller.UserController;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class GUIRegistration extends JFrame {
    private JTextField usernameInput;
    private JPasswordField pwdInput;
    private JButton loginButton;
    private JButton registerNewAccountButton;
    private JPanel userPanel;
    private JLabel username;
    private JLabel pwd;
    private UserController controller = new UserController();

    public GUIRegistration() {
        setContentPane(userPanel);
    }

    public User getUser() {
        // get login user
        String username = usernameInput.getText();
        String pwd = String.valueOf(pwdInput.getPassword());
        User u = this.controller.login(username, pwd);
        return u;
    }

    public User newUserRegistration() {
        String username = usernameInput.getText();
        String pwd = String.valueOf(pwdInput.getPassword());
        User u = null;
        if (username.isEmpty() || pwd.isEmpty())
            return null;
        if (this.controller.signUp(username, pwd, 1)) {
            u = this.controller.login(username, pwd);
        } else { // didn't sign up because user exists
            JOptionPane.showMessageDialog(null, "User already exists, please login.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        return u;
    }

    public void regUpdate() {
        setContentPane(userPanel);
    }

    public JPanel getUserPanel() {
        return userPanel;
    }

    public JButton getLoginButton() {
        return loginButton;
    }

    public JButton getRegisterNewAccountButton() {
        return registerNewAccountButton;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        userPanel = new JPanel();
        userPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        userPanel.setBorder(BorderFactory.createTitledBorder(null, "User Login and Registration", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        username = new JLabel();
        username.setText("Username:");
        userPanel.add(username, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pwd = new JLabel();
        pwd.setText("Password:");
        userPanel.add(pwd, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        usernameInput = new JTextField();
        userPanel.add(usernameInput, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        pwdInput = new JPasswordField();
        userPanel.add(pwdInput, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        loginButton = new JButton();
        loginButton.setText("Login");
        userPanel.add(loginButton, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        registerNewAccountButton = new JButton();
        registerNewAccountButton.setText("Register new account");
        userPanel.add(registerNewAccountButton, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return userPanel;
    }

}
