package gui;

import bean.Stock;
import bean.StockHolding;

import javax.swing.*;
import java.awt.*;
import java.util.List;

public class GUIStockHolding extends JFrame {
    private JLabel stockHoldName;
    private JLabel sidTxt;
    private JLabel qtyTxt;
    private JPanel stockHoldPanel;

    public GUIStockHolding(StockHolding h, List<Stock> stocks) {
        setContentPane(stockHoldPanel);
        String name = "";
        int sid = h.getSid();
        int qty = h.getQuantity();
        sidTxt.setText(String.valueOf(sid));
        qtyTxt.setText(String.valueOf(qty));
        for (Stock s : stocks) {
            if (s.getSid() == sid) {
                name = s.getName();
                break;
            }
        }
        stockHoldName.setText(name);
    }

    public JPanel getStockHoldPanel() {
        return stockHoldPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        stockHoldPanel = new JPanel();
        stockHoldPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        stockHoldName = new JLabel();
        stockHoldName.setText("stockName");
        stockHoldPanel.add(stockHoldName, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        sidTxt = new JLabel();
        sidTxt.setText("sid");
        stockHoldPanel.add(sidTxt, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        qtyTxt = new JLabel();
        qtyTxt.setText("Qty");
        stockHoldPanel.add(qtyTxt, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return stockHoldPanel;
    }
}
