package gui;

import bean.user.Customer;
import bean.user.User;
import controller.AccountOverviewController;
import controller.ManagerController;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

public class GUIUserOverView extends JFrame {
    private CardLayout cards;
    private JPanel usersPanel, listPanel;
    private ManagerController controller;

    public GUIUserOverView(GUIMain home) {
        setContentPane(usersPanel);
        cards = new CardLayout();
        usersPanel.setLayout(cards);
        this.controller = new ManagerController();

        java.util.List<Customer> customers = controller.showCustomers();

        listPanel = new JPanel();
        listPanel.setLayout(new GridLayout(customers.size(), 1));
        for (Customer c : customers) {
            GUIUser user = new GUIUser(c);
            listPanel.add(user.getUserPanel());
        }
        usersPanel.add(listPanel, "Account Panel");
        cards.show(usersPanel, "Account Panel");
    }

    public JPanel getUsersPanel() {
        return usersPanel;
    }

    public void update() {
        setContentPane(usersPanel);
        cards = new CardLayout();
        usersPanel.setLayout(cards);
        this.controller = new ManagerController();

        java.util.List<Customer> customers = controller.showCustomers();

        listPanel = new JPanel();
        listPanel.setLayout(new GridLayout(customers.size(), 1));
        for (Customer c : customers) {
            GUIUser user = new GUIUser(c);
            listPanel.add(user.getUserPanel());
        }
        usersPanel.add(listPanel, "Account Panel");
        cards.show(usersPanel, "Account Panel");
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        usersPanel = new JPanel();
        usersPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return usersPanel;
    }

}
